name: Deploy to Azure WebApp RM1UserList

on:
  push:
    branches:
      - main   # or your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      # Step 2: Setup Node.js (if your app is Node.js)
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      # Step 3: Install and Build
      - name: Install and Build
        run: |
          npm install
          npm run build

      # Step 4: Deploy to Azure WebApp using Publish Profile
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'RM1UserL'   # 👈 your App Service name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./build
